stages:
- test

.check: &check
  stage: test
  image: java:8-jdk-alpine
  script: |
    apk --update add bash libstdc++
    ./gradlew --no-daemon check

check v3.0:
  <<: *check
  variables:
    GRADLE_VERSION_UNDER_TEST: '3.0'

check v3.1:
  <<: *check
  variables:
    GRADLE_VERSION_UNDER_TEST: '3.1'

check v3.2.1:
  <<: *check
  variables:
    GRADLE_VERSION_UNDER_TEST: '3.2.1'

check v3.3:
  <<: *check
  variables:
    GRADLE_VERSION_UNDER_TEST: '3.3'
